interface: wlan1               
log_path: logs/wifi_attack_logs.db 
scan_interval: 2                   
block_method: nftables             
firewall_host: 127.0.0.1           
firewall_port: 9000                
socket_timeout: 5                  
api_port: 5000                     
debug: true                        
log_level: INFO                    
