#!/bin/bash

# WIDRSX System Usage Guide

echo "=========================================="
echo "  WIDRSX Real-time Network Monitor"
echo "  Linux Deployment Guide"
echo "=========================================="
echo ""

echo "🔧 SETUP STEPS:"
echo ""
echo "1. Make scripts executable:"
echo "   chmod +x *.sh widrsx-backend/*.sh"
echo ""
echo "2. Install dependencies:"
echo "   # Ubuntu/Debian:"
echo "   sudo apt install python3 python3-venv nodejs npm wireless-tools aircrack-ng"
echo ""
echo "   # Install Rust:"
echo "   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
echo ""
echo "3. Configure wireless interface in widrsx-backend/config.yaml"
echo "   interface: wlan0  # Change to your interface"
echo ""

echo "🚀 USAGE COMMANDS:"
echo ""
echo "Start everything (Recommended):"
echo "   sudo ./start_widrsx.sh start"
echo ""
echo "Start only backend:"
echo "   sudo ./start_widrsx.sh backend"
echo ""
echo "Start only frontend:"
echo "   ./start_widrsx.sh frontend"
echo ""
echo "Stop all services:"
echo "   sudo ./start_widrsx.sh stop"
echo ""
echo "Check status:"
echo "   ./start_widrsx.sh status"
echo ""

echo "🌐 ACCESS URLs:"
echo ""
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:5000"
echo ""

echo "📱 WEB INTERFACE FEATURES:"
echo ""
echo "   • Start/Stop packet sniffer"
echo "   • Real-time network monitoring"
echo "   • Live threat detection"
echo "   • MAC address blocking"
echo "   • Network statistics dashboard"
echo ""

echo "🔍 TROUBLESHOOTING:"
echo ""
echo "   • Make sure you have a wireless adapter"
echo "   • Run with sudo for network access"
echo "   • Check 'iwconfig' for available interfaces"
echo "   • View logs: tail -f /tmp/api_server.log"
echo ""

echo "⚠️  SECURITY WARNING:"
echo ""
echo "   • Only use on networks you own"
echo "   • Requires root privileges"
echo "   • For educational/authorized testing only"
echo ""

echo "🔗 Quick Start:"
echo ""
echo "   sudo ./start_widrsx.sh start"
echo "   # Then open http://localhost:3000 in browser"
echo ""
echo "=========================================="
